# Generated by Django 5.2.4 on 2025-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
